### ISSUE TITLE
Vanillastack Install failing

### ISSUE THREAD

**Issue by spyfly** [vanillastack/vanillastack#1]
Hi,

I have tried installing Vanillastack using the latest prebuilt docker image, but the install fails with the following message:
![grafik](https://user-images.githubusercontent.com/2892832/93255090-afd12e00-f799-11ea-9f08-c9022dce423e.png)

After this message is displayed, the installer docker container crashes.

I have attached the log output of the docker install container below:
```
> vanilla-backend@0.0.0 start /usr/workdir
> node src/bin/www

Server started on port 8080
GET / 200 7.690 ms - 557
GET /js/index.js 200 1.466 ms - 831681
GET /js/chunk-vendors.js 200 1.777 ms - 1115013
GET /images/vanilla-logo.png 200 0.850 ms - 95327
GET /api/v1/info 200 45.121 ms - 481
GET /favicon.ico 404 2.009 ms - 150
New client connected: 0a030bca-39de-4500-b63f-b7075fcc3b73
Client disconnected: 0a030bca-39de-4500-b63f-b7075fcc3b73
GET / 304 0.623 ms - -
GET /js/chunk-vendors.js 304 0.602 ms - -
GET /js/index.js 304 0.296 ms - -
GET /api/v1/info 200 58.317 ms - 481
GET /images/vanilla-logo.png 304 0.449 ms - -
New client connected: fda8c70b-48ef-41e9-b604-d511d9ea9274
GET /images/rook-prerequisites.png 200 1.433 ms - 57841
POST /api/v1/connection 200 10.367 ms - 27
257274291: Sending Message
stdout:
257274291: Sending Message
Key: sdb
257274291: Sending Message
Key: sdb
257274291: Sending Message
Key: sdb
257274291: Sending Message
257274291 Cleanup done
257274291: Sending Message
GET /images/harbor.png 200 0.964 ms - 140154
GET /images/prometheus.png 200 2.796 ms - 17361
GET /images/grafana.png 200 3.497 ms - 19261
GET /images/fluentd.png 200 3.566 ms - 32356
GET /images/elastic.png 200 3.709 ms - 86058
GET /images/kibana.png 200 2.368 ms - 67244
GET /images/jaeger.png 200 2.974 ms - 12386
GET /images/NGINX-logo.png 200 2.581 ms - 3230
GET /images/kubernetes.png 200 2.369 ms - 24528
GET /images/cert-manager.png 200 2.587 ms - 21837
POST /api/v1/setup 200 3.903 ms - 94
Dry-Run Mode false
912861681: Sending Message
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/workdir/ansible//fda8c70b-48ef-41e9-b604-d511d9ea9274/kubeadm.conf'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at ChildProcess.<anonymous> (/usr/workdir/src/websocket.js:338:37)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/workdir/ansible//fda8c70b-48ef-41e9-b604-d511d9ea9274/kubeadm.conf'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vanilla-backend@0.0.0 start: `node src/bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vanilla-backend@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-15T19_19_41_842Z-debug.log```

**Comment by christiancloudical** [comment]
Hey spyfly,

I can confirm that there is a problem with the path, we are working to fix that as soon as possible,

Greetings,
Christian

**Comment by kisahm** [comment]
@spyfly please checkout the new "latest" image.
`harbor.cloudical.net/vanillastack/installer:latest`

pls remove the old image first.
```
$ docker rmi installer harbor.cloudical.net/vanillastack/installer:latest
$ docker run -p 8080:8080 --name installer harbor.cloudical.net/vanillastack/installer:latest
```

**Comment by spyfly** [comment]
Thanks, the latest image resolved this issue.
